---
- name: Reload Home Assistant Core
  uri:
    url: 'https://homeassistant.{{ domain }}/api/services/{{ item | replace(".", "/") }}'
    method: POST
    body_format: json
    validate_certs: false
    headers:
      Authorization: 'Bearer {{ vault.home_assistant.access_token }}'
  loop:
    - homeassistant.reload_core_config
    - automation.reload
    - group.reload
    - homekit.reload
    - template.reload
- name: Reload Home Assistant UI
  uri:
    url: 'https://homeassistant.{{ domain }}/api/services/{{ item | replace(".", "/") }}'
    method: POST
    body_format: json
    validate_certs: false
    headers:
      Authorization: 'Bearer {{ vault.home_assistant.access_token }}'
  loop:
    - lovelace.reload_resources
    - frontend.reload_themes
