apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: status.${DOMAIN}
  namespace: uptime-kuma
spec:
  secretName: status.${DOMAIN}
  dnsNames:
    - status.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt-production
