# directories
- name: Ensure directories exist
  file:
    path: '{{ paths.root }}/{{ item }}'
    state: directory
  loop:
    - '{{ role_name }}'
    - '{{ role_name }}/config'
    - '{{ role_name }}/data'
    - '{{ role_name }}/backups'
    - '{{ role_name }}/logs'
    - gitlab-runner

# gitlab
- name: Create configuration file
  template:
    src: '{{ role_name }}/gitlab.rb.j2'
    dest: '{{ paths.root }}/{{ role_name }}/config/gitlab.rb'

# gitlab-backups
- name: Ensure backups directory is not empty
  file:
    path: '{{ paths.root }}/{{ role_name }}/backups/.gitlab-backups'
    state: touch

# gitlab-runner
- name: Create runner configuration file
  template:
    src: gitlab-runner/config.toml.j2
    dest: '{{ paths.root }}/gitlab-runner/config.toml'
