---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-errors
  namespace: traefik-errors
spec:
  chart:
    spec:
      chart: traefik-errors
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/pascaliske/traefik-errors
      tag: 1.0.5
    ingressRoute:
      create: true
      entryPoints:
        - http
        - https
      rule: HostRegexp(`{host:.+}`)
      middlewares:
        - name: security
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    middleware:
      create: true
      name: error-pages
      statusCodes:
        - '404'
        - '410-599'
      homeUrl: https://${DOMAIN}
    env:
      - name: TZ
        value: ${TIMEZONE}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  interval: 10m0s
