---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-errors
  namespace: traefik-errors
spec:
  chart:
    spec:
      chart: traefik-errors
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/pascaliske/traefik-errors
      tag: 1.0.3
    ingressRoute:
      create: true
      entryPoints:
        - http
        - https
      rule: HostRegexp(`{host:.+}`)
      middlewares:
        - name: security
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
    middleware:
      create: true
      name: error-pages
      homeUrl: https://${DOMAIN}
    env:
      - name: TZ
        value: ${TIMEZONE}
  interval: 10m0s
