alias: CPU Temperature Alarm
trigger:
  platform: numeric_state
  entity_id: sensor.cpu_temperature
  above: 69
action:
  - service: notify.slack
    data:
      title: CPU Temperature Alarm
      message: >
        :sweat: System is getting too hot: {{ states('sensor.cpu_temperature') }}°C
