alias: CPU Temperature Alarm
trigger:
  platform: numeric_state
  entity_id: sensor.cpu_temperature
  above: 69
condition:
  condition: template
  value_template: >
    {{ (as_timestamp(now()) - as_timestamp(state_attr('automation.cpu_temperature_alarm', 'last_triggered') | default(0)) | int > 1800) }}
action:
  - service: notify.slack
    data:
      title: CPU Temperature Alarm
      message: >
        :sweat: System is getting too hot: {{ states('sensor.cpu_temperature') }}°C
