alias: Disk Use Alarm
trigger:
  platform: numeric_state
  entity_id: sensor.disk_use_percent
  above: 90
condition:
  condition: template
  value_template: >
    {{ (as_timestamp(now()) - as_timestamp(state_attr('automation.disk_use_alarm', 'last_triggered') | default(0)) | int > 600)}}
action:
  - service: notify.slack
    data_template:
      title: Hard Drive Monitor
      message: >
        :floppy_disk: System is running out of space: {{ states('sensor.disk_use_percent') }}%
  - service: persistent_notification.create
    data_template:
      title: Hard Drive Monitor
      message: >
        System is running out of space: {{ states('sensor.disk_use_percent') }}%
      notification_id: "Hard Drive Monitor"
