alias: Entrance Notification
trigger:
  platform: state
  entity_id:
    - binary_sensor.entrance_door_lumi_contact
  from: 'off'
  to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
action:
  service: notify.slack
  data_template:
    title: Entrance Open
    message: >
      :door: The {{ trigger.to_state.attributes.friendly_name }} was opened!
