---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  chart:
    spec:
      chart: paperless
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.7
    env:
      - name: TZ
        value: ${TIMEZONE}
      - name: PAPERLESS_URL
        value: https://docs.${DOMAIN_EXTERNAL}
      - name: PAPERLESS_ALLOWED_HOSTS
        value: '*'
      - name: PAPERLESS_REDIS
        value: redis://redis.redis.svc.cluster.local:6379
      - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
        value: 'true'
      - name: PAPERLESS_OCR_LANGUAGE
        value: deu
      - name: PAPERLESS_IGNORE_DATES
        value: ${PAPERLESS_IGNORE_DATES}
    secret:
      create: true
      secretKey: ${PAPERLESS_SECRET_KEY}
    consumption:
      enabled: true
      hostPath: ${PATH_HOME}/paperless/import
    export:
      enabled: true
      hostPath: ${PATH_HOME}/paperless/export
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: k8s.pascaliske.dev/location
                  operator: In
                  values:
                    - public
    tolerations:
      - key: k8s.pascaliske.dev/location
        operator: Equal
        value: public
        effect: NoSchedule
  interval: 10m0s
