---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis
  - authelia
  - traefik
  - cloudflared
  - blocky
  - unifi
  - uptime-kuma
  - homer
  - home-assistant
  - dyndns
  - shlink
  - gitlab
  - code-server
  - linkding
  - snapdrop
  - paperless
  # - monitoring
  - vaultwarden
