---
rules:
  - policy: bypass
    services:
      - git
      - registry
      - portainer
  - policy: bypass
    resources:
      - ^\/api
    services:
      - docs
  - policy: two_factor
    services:
      - traefik
      - code
      - links
      - docs
      - logs
