alias: Ad Blocking Alarm
trigger:
  platform: numeric_state
  entity_id: sensor.pi_hole_ads_percentage_blocked_today
  below: 10
action:
  - service: notify.slack
    data_template:
      title: Ad Blocking Alarm
      message: >
        Ad Blocking percentage dropped below limit: {{ states('sensor.pi_hole_ads_percentage_blocked_today') }}%
