---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia.yaml
  - jetstack.yaml
  - k8s-at-home.yaml
  - keel.yaml
  - pascaliske.yaml
  - traefik.yaml
  - vmware-tanzu.yaml
