---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers
  namespace: unifi
spec:
  headers:
    accessControlAllowCredentials: true
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    # sslHost: unifi.${DOMAIN_INTERNAL} # TODO: deprecated
    # sslRedirect: true # TODO: deprecated
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 315360000
