route:
  receiver: slack

receivers:
  - name: slack
    slack_configs:
      - channel: '#alerts'
        username: Prometheus
        api_url: 'https://hooks.slack.com/services/xyz'
        text: '{{ .CommonAnnotations.description }}'
        send_resolved: true
