language: minimal
services:
  - docker
before_install:
  - mv roles/home-assistant/templates/integrations/http.yaml{,.disabled}
  - mv roles/home-assistant/templates/integrations/withings.yaml{,.disabled}
script:
  - docker run -v $(pwd)/roles/home-assistant/templates:/config homeassistant/home-assistant:stable hass --script check_config --config /config
