version: '3'

includes:
  docs: ./.github/taskfiles/docs.yml

tasks:
  tf:init:
    dir: terraform
    cmds:
      - terraform init {{.CLI_ARGS}}
  tf:plan:
    dir: terraform
    cmds:
      - terraform plan {{.CLI_ARGS}}
  tf:apply:
    dir: terraform
    cmds:
      - terraform apply {{.CLI_ARGS}}
  tf:lint:
    dir: terraform
    cmds:
      - tflint --format compact .
  docs:
    summary: Documentation specific tasks.
    cmds:
      - task: docs:default
      - for file in cluster/**/README.md; do mkdir -p docs/$(dirname $file) && cp $file docs/$(dirname $file)/index.md; done
      - for file in cluster/**/**/README.md; do mkdir -p docs/$(dirname $file) && cp $file docs/$(dirname $file)/index.md; done
      - for file in cluster/**/**/**/README.md; do mkdir -p docs/$(dirname $file) && cp $file docs/$(dirname $file)/index.md; done
