# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  tf: ./.github/taskfiles/terraform.yml
  vault: ./.github/taskfiles/vault.yml
  sops: ./.github/taskfiles/sops.yml
  cluster: ./.github/taskfiles/cluster.yml
  blocky: ./.github/taskfiles/blocky.yml
  backup: ./.github/taskfiles/backup.yml
  docs: ./.github/taskfiles/docs.yml

tasks:
  install:
    summary: Install all related dependencies
    cmds:
      - yarn install
      - cd ansible && ansible-galaxy install -r requirements.yml

  docs:
    summary: Documentation specific tasks.
    cmds:
      - task: docs:default
      - for file in cluster/**/README.md; do mkdir -p docs/$(dirname $file) && cp $file docs/$(dirname $file)/index.md; done
      - for file in cluster/**/**/README.md; do mkdir -p docs/$(dirname $file) && cp $file docs/$(dirname $file)/index.md; done
      - for file in cluster/**/**/**/README.md; do mkdir -p docs/$(dirname $file) && cp $file docs/$(dirname $file)/index.md; done
