---
alertmanager_slack_channel: "{{ lookup('env', 'ALERTMANAGER_SLACK_CHANNEL') }}"
alertmanager_slack_username: "{{ lookup('env', 'ALERTMANAGER_SLACK_USERNAME') }}"
alertmanager_slack_webhook: "{{ lookup('env', 'ALERTMANAGER_SLACK_WEBHOOK') }}"
