---
rules:
  # exceptions
  - policy: bypass
    services:
      - unifi
      - vault
  - policy: bypass
    resources:
      - /-/reload
    services:
      - alerts
      - prometheus
  - policy: bypass
    resources:
      - /ready
      - /loki/api/v1/push
    services:
      - loki
  - policy: bypass
    resources:
      - /api/services
      - /api/websocket
    services:
      - homeassistant
  - policy: bypass
    resources:
      - ^\/assets
      - ^\/icon
      - ^\/manifest
      - /status
    services:
      - status

  # two factor
  - policy: two_factor
    services:
      - alerts
      - grafana
      - homeassistant
      - keel
      - prometheus
      - status
      - traefik
  - policy: two_factor
    resources:
      - /admin
    services:
      - vault
