---
default_redirection_url: 'https://{{ domain }}'
rules:
  # exceptions
  - policy: bypass
    services:
      - unifi
      - vault
  - policy: bypass
    resources:
      - /-/reload
    services:
      - alerts
      - prometheus
  - policy: bypass
    resources:
      - ^\/+api\.php
    services:
      - pihole
  - policy: bypass
    resources:
      - /ready
      - /loki/api/v1/push
    services:
      - loki
  - policy: bypass
    resources:
      - /api/services
      - /api/websocket
    services:
      - homeassistant

  # two factor
  - policy: two_factor
    services:
      - alerts
      - grafana
      - homeassistant
      - pihole
      - prometheus
      - status
      - traefik
  - policy: two_factor
    resources:
      - /admin
    services:
      - vault
