apiVersion: 1
datasources:
  - type: prometheus
    name: Prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
  - type: loki
    name: Loki
    uid: loki
    url: http://loki:3100
    access: proxy
    editable: false
