---
rules:
  - policy: bypass
    services:
      - unifi
      - portainer
  - policy: bypass
    resources:
      - /-/reload
    services:
      - prometheus
      - alerts
  - policy: bypass
    resources:
      - ^\/+api\.php
    services:
      - pihole
  - policy: bypass
    resources:
      - /ready
      - /loki/api/v1/push
    services:
      - loki
  - policy: two_factor
    services:
      - traefik
      - prometheus
      - grafana
      - alerts
      - pihole
      - homeassistant
      - dozzle
