# directories
- name: Ensure directories exist
  file:
    path: '{{ paths.root }}/{{ item }}'
    state: directory
  loop:
    - '{{ role_name }}'
    - '{{ role_name }}/themes'
    - '{{ role_name }}/www'

# namespace
- name: Create a namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: '{{ role_name }}'
    state: present

# configuration
- name: Copy Home Assistant config files
  synchronize:
    src: ../files/{{ item }}.yaml
    dest: '{{ paths.root }}/{{ role_name }}/{{ item }}.yaml'
  loop:
    - configuration
    - customize
    - ui-lovelace
  notify: Reload Home Assistant Core
- name: Copy Home Assistant config directories
  synchronize:
    src: ../files/{{ item }}/
    dest: '{{ paths.root }}/{{ role_name }}/{{ item }}'
    delete: yes
  loop:
    - automations
    - groups
    - integrations
    - scenes
    - scripts
    - sensors
    - switches
    - views
  notify: Reload Home Assistant Core

# configuration / secrets
- name: Copy Home Assistant secrets to config directory
  template:
    src: home-assistant/secrets.yml.j2
    dest: '{{ paths.root }}/{{ role_name }}/secrets.yaml'
  notify: Reload Home Assistant Core

# configuration / themes
- name: Download themes into theme directory
  block:
    - name: Download theme into theme directory
      get_url:
        url: '{{ item.url }}'
        dest: '{{ paths.root }}/{{ role_name }}/themes/{{ item.name }}.yaml'
      loop: '{{ themes.url }}'
  notify: Reload Home Assistant UI

# configuration / cards
- name: Clone cards into www directory
  block:
    - name: Clone card into www directory
      git:
        repo: 'https://github.com/{{ item.user }}/{{ item.repo }}.git'
        version: master
        dest: '{{ paths.root }}/{{ role_name }}/www/{{ item.repo }}'
        force: yes
      loop: '{{ cards.git }}'
      diff: no
  notify: Reload Home Assistant UI
- name: Download cards into www directory
  block:
    - name: Ensure card folders exist
      file:
        path: '{{ paths.root }}/{{ role_name }}/www/{{ item.repo }}'
        state: directory
      loop: '{{ cards.url }}'
    - name: Download card into card directory
      get_url:
        url: 'https://github.com/{{ item.user }}/{{ item.repo }}/releases/latest/download/{{ item.file | default(item.repo) }}.js'
        dest: '{{ paths.root }}/{{ role_name }}/www/{{ item.repo }}/'
      loop: '{{ cards.url }}'
  notify: Reload Home Assistant UI

# home-assistant
- name: Add helm repo
  kubernetes.core.helm_repository:
    name: k8s-at-home
    repo_url: https://k8s-at-home.com/charts

- name: Create chart values file
  template:
    src: '{{ role_name }}/values.yml.j2'
    dest: '{{ paths.root }}/{{ role_name }}/values.yml'

- name: Apply helm chart with values file
  kubernetes.core.helm:
    name: '{{ role_name }}'
    chart_ref: 'k8s-at-home/{{ role_name }}'
    namespace: '{{ role_name }}'
    update_repo_cache: yes
    values_files:
      - '{{ paths.root }}/{{ role_name }}/values.yml'

# route
- name: Create ingress route
  kubernetes.core.k8s:
    state: present
    template: '{{ role_name }}/route.yml.j2'
