# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ role_name }}/{{ item }}'
    state: directory
  loop:
    - custom_components
    - themes
    - www

# config files
- name: Copy Home Assistant config files
  synchronize:
    src: ../files/{{ item }}.yaml
    dest: '{{ root_path }}/{{ role_name }}/{{ item }}.yaml'
  loop:
    - configuration
    - customize
    - ui-lovelace
  notify: Reload Home Assistant Core
- name: Copy Home Assistant config directories
  synchronize:
    src: ../files/{{ item }}/
    dest: '{{ root_path }}/{{ role_name }}/{{ item }}'
    delete: yes
  loop:
    - automations
    - groups
    - integrations
    - scenes
    - scripts
    - sensors
    - switches
    - views
  notify: Reload Home Assistant Core

# secrets
- name: Copy Home Assistant secrets to config directory
  template:
    src: home-assistant/secrets.yml.j2
    dest: '{{ root_path }}/{{ role_name }}/secrets.yaml'
  notify: Reload Home Assistant Core

# themes
- name: Download themes into theme directory
  block:
    - name: Download theme into theme directory
      get_url:
        url: '{{ item.url }}'
        dest: '{{ root_path }}/{{ role_name }}/themes/{{ item.name }}.yaml'
      loop: '{{ themes.url }}'
  notify: Reload Home Assistant UI

# cards
- name: Clone cards into www directory
  block:
    - name: Clone card into www directory
      git:
        repo: 'https://github.com/{{ item.user }}/{{ item.repo }}.git'
        version: master
        dest: '{{ root_path }}/{{ role_name }}/www/{{ item.repo }}'
        force: yes
      loop: '{{ cards.git }}'
      diff: no
  notify: Reload Home Assistant UI
- name: Download cards into www directory
  block:
    - name: Ensure card folders exist
      file:
        path: '{{ root_path }}/{{ role_name }}/www/{{ item.repo }}'
        state: directory
      loop: '{{ cards.url }}'
    - name: Download card into card directory
      get_url:
        url: 'https://github.com/{{ item.user }}/{{ item.repo }}/releases/latest/download/{{ item.file | default(item.repo) }}.js'
        dest: '{{ root_path }}/{{ role_name }}/www/{{ item.repo }}/'
      loop: '{{ cards.url }}'
  notify: Reload Home Assistant UI

# components
- name: Download HACS components into custom_components directory
  block:
    - name: Ensure component folders exist
      file:
        path: '{{ root_path }}/{{ role_name }}/custom_components/{{ item.repo }}'
        state: directory
      loop: '{{ components.url }}'
    - name: Download component into components directory
      unarchive:
        src: 'https://github.com/{{ item.user }}/{{ item.repo }}/releases/latest/download/{{ item.file | default(item.repo) }}.zip'
        dest: '{{ root_path }}/{{ role_name }}/custom_components/{{ item.repo }}'
        remote_src: yes
      loop: '{{ components.url }}'
  notify: Reload Home Assistant UI
