# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ role_name }}/{{ item }}'
    state: directory
  loop:
    - themes
    - www

# config files
- name: Copy Home Assistant config files
  synchronize:
    src: ../files/{{ item }}.yaml
    dest: '{{ root_path }}/{{ role_name }}/{{ item }}.yaml'
  loop:
    - configuration
    - customize
    - ui-lovelace

- name: Copy Home Assistant config directories
  synchronize:
    src: ../files/{{ item }}/
    dest: '{{ root_path }}/{{ role_name }}/{{ item }}'
    delete: yes
  loop:
    - automations
    - groups
    - integrations
    - scenes
    - scripts
    - sensors
    - switches
    - views

- name: Copy Home Assistant secrets to config directory
  template:
    src: home-assistant/secrets.yml.j2
    dest: '{{ root_path }}/{{ role_name }}/secrets.yaml'

# themes
- name: Download themes into theme directory
  get_url:
    url: '{{ item.url }}'
    dest: '{{ root_path }}/{{ role_name }}/themes/{{ item.name }}.yaml'
  loop:
    - { name: 'google-home', url: 'https://raw.githubusercontent.com/liri/lovelace-themes/master/themes/google-home.yaml' }


# plugins
- name: Clone plugins into plugin directory
  git:
    repo: 'https://github.com/{{ item.user }}/{{ item.repo }}.git'
    version: master
    dest: '{{ root_path }}/{{ role_name }}/www/{{ item.repo }}'
    force: yes
  loop:
    - { user: 'benct', repo: 'lovelace-github-entity-row' }
    - { user: 'benct', repo: 'lovelace-multiple-entity-row' }
    - { user: 'cbulock', repo: 'lovelace-battery-entity' }
    - { user: 'thomasloven', repo: 'lovelace-card-mod' }
    - { user: 'thomasloven', repo: 'lovelace-slider-entity-row' }

- name: Download plugins into plugin directory
  vars:
    plugins:
      - { folder: 'mini-graph-card', url: 'https://github.com/kalkih/mini-graph-card/releases/latest/download/mini-graph-card-bundle.js' }
      - { folder: 'text-divider-row', url: 'https://github.com/iantrich/text-divider-row/releases/latest/download/text-divider-row.js' }
  block:
    - name: Ensure plugin folders exist
      file:
        path: '{{ root_path }}/{{ role_name }}/www/{{ item.folder }}'
        state: directory
      loop: '{{ plugins }}'
    - name: Download plugins into plugin directory
      get_url:
        url: '{{ item.url }}'
        dest: '{{ root_path }}/{{ role_name }}/www/{{ item.folder }}/'
      loop: '{{ plugins }}'
