- name: Ensure config directories exists
  file:
    path: '{{ root_path }}/{{ role_name }}'
    state: directory

- name: Copy Home Assistant files to config directory
  copy:
    src: ../templates/
    dest: '{{ root_path }}/{{ role_name }}'
