apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn.${DOMAIN}
  namespace: longhorn
spec:
  secretName: longhorn.${DOMAIN}
  dnsNames:
    - longhorn.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt-production
