apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn
  namespace: longhorn
spec:
  endpoints:
    - port: manager
  selector:
    matchLabels:
      app: longhorn-manager
