---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers
  namespace: authelia
spec:
  headers:
    browserXssFilter: true
    customFrameOptionsValue: SAMEORIGIN
    customResponseHeaders:
      Cache-Control: no-store
      Pragma: no-cache
