---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: velero-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: velero-source
  interval: 15m
  prune: false
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: backups.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: backupstoragelocations.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: deletebackuprequests.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: downloadrequests.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podvolumebackups.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podvolumerestores.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: resticrepositories.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: restores.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: schedules.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: serverstatusrequests.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: volumesnapshotlocations.velero.io
