---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  TIMEZONE: Europe/Berlin
  DOMAIN: iske.cloud
  DOMAIN_EXTERNAL: pascaliske.dev
  UID: '1000'
  GID: '1000'
