- platform: github
  access_token: !secret github_token
  repositories:
    - path: pascaliske/infrastructure

- platform: template
  sensors:
    infrastructure_open_issues:
      friendly_name: Open issues
      unit_of_measurement: ''
      value_template: >
        {{ state_attr('sensor.infrastructure', 'open_issues') or '0' }}
    infrastructure_latest_open_issue_url:
      friendly_name: Latest open issue url
      unit_of_measurement: ''
      value_template: >
        {{ state_attr('sensor.infrastructure', 'latest_open_issue_url') or '' }}
    infrastructure_open_pull_requests:
      friendly_name: Open pull requests
      unit_of_measurement: ''
      value_template: >
        {{ state_attr('sensor.infrastructure', 'open_pull_requests') or '0' }}
    infrastructure_latest_open_pull_request_url:
      friendly_name: Latest open pull request url
      unit_of_measurement: ''
      value_template: >
        {{ state_attr('sensor.infrastructure', 'latest_open_pull_request_url') or '' }}
