# system monitor
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: ipv4_address
      arg: eth0
    - type: last_boot

# relative last boot
- platform: template
  sensors:
    relative_last_boot:
      friendly_name: Relative Last Boot
      value_template: >
        {% set date = strptime(states('sensor.last_boot'), '%Y-%m-%dT%H:%M:%S%z') %}
        {% set diff = now() - date %}
        {{ diff.days }}
      unit_of_measurement: days ago
