---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkding
  namespace: linkding
spec:
  chart:
    spec:
      chart: linkding
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: sissbruecker/linkding
      tag: 1.11.0

    env:
      - name: TZ
        value: ${TIMEZONE}
  interval: 10m0s
