apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drop.${DOMAIN}
  namespace: snapdrop
spec:
  secretName: drop.${DOMAIN}
  dnsNames:
    - drop.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt-production
