# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - prometheus
    - alertmanager
    - grafana
    - grafana/provisioning
    - unifi-exporter

# prometheus
- name: Configure Prometheus
  vars:
    item: prometheus
  block:
    - name: Create Prometheus config
      template:
        src: '{{ item }}/{{ item }}.yml.j2'
        dest: '{{ root_path }}/{{ item }}/{{ item }}.yml'
      notify: Reload Prometheus
    - name: Create alert rules config
      template:
        src: '{{ item }}/alert.rules.j2'
        dest: '{{ root_path }}/{{ item }}/alert.rules'
      notify: Reload Prometheus

# alertmanager
- name: Configure Alertmanager
  vars:
    item: alertmanager
  block:
    - name: Create Alertmanager config
      template:
        src: '{{ item }}/{{ item }}.yml.j2'
        dest: '{{ root_path }}/{{ item }}/{{ item }}.yml'
      notify: Reload Alertmanager

# grafana
- name: Configure Grafana
  vars:
    item: grafana
  block:
    - name: Create Grafana config file
      template:
        src: '{{ item }}/grafana.ini.j2'
        dest: '{{ root_path }}/{{ item }}/grafana.ini'
    - name: Copy Grafana Provisioning files to config directory
      synchronize:
        src: ../files/{{ item }}/provisioning
        dest: '{{ root_path }}/{{ item }}'
        delete: yes

# unifi-exporter
- name: Configure UniFi Exporter
  vars:
    item: unifi-exporter
  block:
    - name: Create UniFi Exporter config
      template:
        src: '{{ item }}/unifi-poller.conf.j2'
        dest: '{{ root_path }}/{{ item }}/unifi-poller.conf'
