# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop: '{{ services + exporters }}'

# namespace
- name: Create a namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: '{{ role_name }}'
    state: present

# services
- name: Configure services
  include_tasks: 'services/{{ service }}/main.yml'
  loop: '{{ services }}'
  loop_control:
    loop_var: service

# exporters
- name: Configure exporters
  include_tasks: 'exporters/{{ exporter }}/main.yml'
  loop: '{{ exporters }}'
  loop_control:
    loop_var: exporter
