- name: Ensure config directories exists.
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - prometheus
    - alertmanager
    - grafana
    - unifi-exporter

- name: Configure Prometheus
  vars:
    item: prometheus
  block:
    - name: Copy prometheus config to config directory.
      template:
        src: ../templates/{{ item }}/config.tpl
        dest: '{{ root_path }}/{{ item }}/{{ item }}.yml'
    - name: Copy prometheus alert rules to config directory.
      template:
        src: ../templates/{{ item }}/alert.rules.tpl
        dest: '{{ root_path }}/{{ item }}/alert.rules'

- name: Configure Alertmanager
  vars:
    item: alertmanager
  block:
    - name: Copy alertmanager config to config directory.
      template:
        src: ../templates/{{ item }}/config.tpl
        dest: '{{ root_path }}/{{ item }}/config.yml'

- name: Configure Grafana
  vars:
    item: grafana
  block:
    - name: Provisioning Grafana.
      copy:
        src: ../templates/{{ item }}/provisioning
        dest: '{{ root_path }}/{{ item }}'

- name: Configure UniFi Exporter
  vars:
    item: unifi-exporter
  block:
    - name: Copy unifi-exporter config to config directory.
      template:
        src: ../templates/{{ item }}/config.tpl
        dest: '{{ root_path }}/{{ item }}/config.yml'
