# directories
- name: Ensure directories exist
  file:
    path: '{{ paths.root }}/{{ item }}'
    state: directory
  loop: '{{ services + exporters }}'

# namespace
- include_tasks: '{{ inventory_dir }}/roles/k3s/tasks/namespace.yml'

# services
- name: Configure services
  include_tasks: 'services/{{ service }}/main.yml'
  loop: '{{ services }}'
  loop_control:
    loop_var: service

# exporters
- name: Configure exporters
  include_tasks: 'exporters/{{ exporter }}/main.yml'
  loop: '{{ exporters }}'
  loop_control:
    loop_var: exporter
