homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named integrations
  auth_providers:
    - type: homeassistant
http:
  ssl_certificate: /config/fullchain.pem
  ssl_key: /config/privkey.pem
lovelace:
  mode: yaml
  resources:
    - url: /local/lovelace-card-mod/card-mod.js
      type: module
