homeassistant:
  customize: !include customize.yaml

tts:
  - platform: google_translate

default_config:
frontend:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
