# directories
- name: Ensure directories exist
  file:
    path: '{{ paths.root }}/{{ item }}'
    state: directory
  loop:
    - '{{ role_name }}'

# glances
- name: Create configuration file
  template:
    src: '{{ role_name }}/glances.conf.j2'
    dest: '{{ paths.root }}/{{ role_name }}/glances.conf'
