---
- name: configure
  hosts: remote
  roles:
    - role: common
      tags:
        - common
    - role: k3s
      tags:
        - k3s
    - role: traefik
      tags:
        - traefik
    - role: autorestic
      tags:
        - autorestic
    - role: authelia
      tags:
        - authelia
    - role: fail2ban
      tags:
        - fail2ban
    - role: gitlab
      tags:
        - gitlab
    - role: code-server
      tags:
        - code-server
    - role: glances
      tags:
        - glances
    - role: linkding
      tags:
        - linkding
    - role: paperless
      tags:
        - paperless
