apiVersion: v1
kind: Secret
metadata:
    name: plausible-secrets
    namespace: plausible
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:SW9PMkwHYeFNZ7Xnj7533EoiW1d9ymWdR8yTJujR+vGYZJMxU5F80JUNDSxxKRUgghT+DoZdBNAoyI9LeefE8rWxKkOdpP6lhOXlp1lbSLEZdb7RqkoF0Q==,iv:D2DPj7qKhQ2Jn1tkuH5XR+vdpniUp5PZ1f2UggQoTi0=,tag:usYDTvefWOjnjNtNoR2Olg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:nUwPt46FC173byp+PxS95/rAsK4Z71ahRGGD0F+gC1AqEHjh8ck5IxtmhMPxgtWM5XZAdQ6IQCKcel8u4KMLi1RVrDxmDj2ZPjkU9piwCjLAUB6qB4hhWJTGCPQ=,iv:TVAoGwW1Gdoavr50zjgb5Yj93AOCdWuJmnMC/He683g=,tag:qEFf9HV9ngr2RFEx+60NRw==,type:str]
    CLICKHOUSE_DATABASE_URL: ENC[AES256_GCM,data:OLi1Ty8gU/s49DVUncfF4J3uDOcTltTQbgRkkLrebdSVkgWJakdektb8DEcSwutaOClrNtZbz3NYLqa2Fw==,iv:b61Vdf7Z3TH0lICFCiIQZo/jXXOumBxyG1hVw4DhTcU=,tag:cMrcxLrzMXasC96goQnYCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1znmsndwgl8f4wxn5ydl3f0gkcvcz5uqd5zeervevmmsaygwvrfysgx8xpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdFFPV0NXZUxGdm41Qm90
            WlRwQ2xPRjk3YS9yOXBYUzBqV3dPZTBhWGd3CmkrZm1wcHdTb2tyM0hqWDV5MlNO
            VUpEN3ZESkpqRnJtQzBDT3hLSTJqdlkKLS0tIGxLV2hiRW5xUzdwUmRkSnNZK3Mv
            b0tBYXl4SlVubTZZbDdoVFpLeFdCZVEKypbmIyH15Xwrn8D3CEHqviD3HQy9glWo
            uwC96BM2i8Ey38V+1tIopyXUhhgUJKh7eJGQY1YWuFdP1CVbcqJwog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T10:17:02Z"
    mac: ENC[AES256_GCM,data:iaadf8ZMU23Yg0YmvIcNqvKkSWxTGB7I2U9/lGpJV7r0A0OCvIU7d79z6guJX0k0VFnnNoboLWF3MXl6YDspxAqA4c+xcq/OyGHnrDta6qWClzcOX8j78fC9+f92j59/CU02m+KadBjXe6TjQnJXhAIXNNJBLAeDvnQ6XJojERw=,iv:aS/2BInmnmj74CYx9MAuRWiBkXFnWp6dx0fkNTz9noE=,tag:OiqdnazKJf6CkdxEGIrRJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
