---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: shlink
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`go.${DOMAIN_EXTERNAL}`)
      services:
        - kind: Service
          name: shlink
          namespace: shlink
          port: 8080
      middlewares:
        - name: auth-external
          namespace: traefik
        - name: security
          namespace: traefik
        - name: error-pages
          namespace: traefik-errors
  tls:
    secretName: go.${DOMAIN_EXTERNAL}
