---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-production
spec:
  acme:
    email: '${AUTH_EMAIL}'
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: '${AUTH_EMAIL}'
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
