---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  chart:
    spec:
      chart: clickhouse
      version: '0.2.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: clickhouse/clickhouse-server
      tag: 23.2.1.2537-alpine
    env:
      - name: TZ
        value: ${TIMEZONE}
  interval: 10m0s
