---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
  values:
    defaultSettings:
      taintToleration: k8s.pascaliske.dev/location=public:NoSchedule
    longhornManager:
      tolerations:
        - key: k8s.pascaliske.dev/location
          operator: Equal
          value: public
          effect: NoSchedule
    longhornDriver:
      tolerations:
        - key: k8s.pascaliske.dev/location
          operator: Equal
          value: public
          effect: NoSchedule
  interval: 10m0s
