---
- name: network
  hosts: network
  roles:
    - role: common
      tags:
        - common
    - role: autorestic
      tags:
        - autorestic
    - role: authelia
      tags:
        - authelia
    - role: fail2ban
      tags:
        - fail2ban
    - role: homer
      tags:
        - homer
    - role: monitoring
      tags:
        - monitoring
    - role: pihole
      tags:
        - pihole
    - role: home-assistant
      tags:
        - home-assistant
