---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-external
  namespace: traefik
spec:
  forwardAuth:
    address: http://authelia-external.authelia.svc.cluster.local/api/verify?rd=https://auth.${DOMAIN_EXTERNAL}
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
