apiVersion: v1
kind: Secret
metadata:
    name: slack-webhook-url
    namespace: flux-system
type: Opaque
data:
    address: ENC[AES256_GCM,data:EafhoiewviEAqLBloLxB1elVEsqSjJGehtY3nFTkwuuE1Uky9LK9Hg8e6GGoSMhQVyep7qNmzaNMmiuBKGyLiLioZSGgVGfQ69R65Elb63W7FVYYhP7G7ywJN21aQ8MaZQmXLf7Si6PDOgbL,iv:FRBBzId9VTAycob055JmcTpk5NdljMfGZYkCdX03RlM=,tag:6+MuW1WS1/JwRUfFANQwwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1znmsndwgl8f4wxn5ydl3f0gkcvcz5uqd5zeervevmmsaygwvrfysgx8xpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U3J1WDV1QXltWU02ZDB6
            VXA3Q2VlSHcraDl3dGJiRVM3UEU0NzQvUlVvCk9jeGxLbEhKUjVhUHpCOUFPVDdC
            elFDaHRzMlc5UElwSEl3czR2R3J3VFUKLS0tIFJIU1FvenRvaFkrYW44ZjA0Mko2
            UDNBQ0N2bno4QnNmSnZGeS90VWcwWDgK6b+sD54L90sA0SxjSt/hK3lm0bpbykId
            k+iwKH31jQfhFzsboLK4vEmwbJWXPmcAeyTtuLpsioffeeRcz1yx1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-11T22:27:35Z"
    mac: ENC[AES256_GCM,data:wBRRP51uY648JAIMPyPfP5HSUECtYYLlnG1pa49kuy28nXlDzvtfPSdafMEYuqUnQDRNPxReNyPuodYrwuaO7Bn+iwKmTMZQpzgKQdBOaiAIeIxYS7Nw3s9aERCFhl+4zN6U+xrNH3cR6ykRGZitb6OET+I4dKTVCR0a/odv89c=,iv:2iSgOT5jH2Dr7kMya8OAafVmSdNQ8uv9qacHKaUzPm4=,tag:ai+XuNdvlztl6Sm401fJBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
