# variables
- name: Load host specific variables
  include_vars:
    file: '{{ ansible_play_name }}/main.yml'
    name: '{{ ansible_play_name }}'

# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - '{{ role_name }}'

- name: Create configuration file
  template:
    src: '{{ role_name }}/configuration.yml.j2'
    dest: '{{ root_path }}/{{ role_name }}/configuration.yml'

- name: Create users file
  template:
    src: '{{ role_name }}/users.yml.j2'
    dest: '{{ root_path }}/{{ role_name }}/users.yml'
