homekit:
  filter:
    include_domains:
      - light
      - switch
      - media_player
    include_entity_globs:
      - sensor.*_lumi_*
      - binary_sensor.*_lumi_*
    exclude_entities:
      - switch.network_controller
    exclude_entity_globs:
      - switch.pi_hole_*
  entity_config:
    media_player.spotify_pascal_iske:
      feature_list:
        - feature: play_pause
    media_player.ps4_pi:
      feature_list:
        - feature: on_off
