http:
  routers:
    homeassistant:
      rule: Host(`homeassistant.{{ domain }}`)
      entryPoints:
        - https
      service: homeassistant
      tls: true
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: https://dockerhost:8123
