http:
  routers:
    homeassistant:
      rule: Host(`homeassistant.{{ domain }}`)
      entryPoints:
        - https
      service: homeassistant
      middlewares:
        - auth@file
      tls:
        certResolver: digitalocean
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: https://dockerhost:8123
