- name: Ensure config directory exists
  file:
    path: '{{ root_path }}/{{ role_name }}'
    state: directory

- name: Ensure assets directory exists
  file:
    path: '{{ root_path }}/{{ role_name }}/assets'
    state: directory

- name: Copy config file to config directory
  template:
    src: ../templates/config.yml
    dest: '{{ root_path }}/{{ role_name }}/config.yml'

- name: Copy assets to assets directory
  synchronize:
    src: ../files/
    dest: '{{ root_path }}/{{ role_name }}/assets'
