# variables
- name: Load host specific variables
  include_vars:
    file: '{{ ansible_play_name }}/main.yml'
    name: '{{ ansible_play_name }}'

# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ role_name }}/{{ item }}'
    state: directory
  loop:
    - assets

# config files
- name: Create configuration file
  template:
    src: homer/config.yml.j2
    dest: '{{ root_path }}/{{ role_name }}/config.yml'

# assets
- name: Copy assets to assets directory
  synchronize:
    src: ../files/
    dest: '{{ root_path }}/{{ role_name }}/assets'
