# general
host: 0.0.0.0
port: 9091
jwt_secret: '{{ auth_jwt_secret }}'
default_redirection_url: 'https://{{ domain }}'
totp:
  issuer: '{{ domain }}'

authentication_backend:
  file:
    path: /config/users.yml
    password:
      algorithm: sha512
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 128

access_control:
  default_policy: deny
  rules:
    - domain: 'dozzle.{{ domain }}'
      policy: one_factor
    - domain: 'traefik.{{ domain }}'
      policy: one_factor
    - domain: 'prometheus.{{ domain }}'
      policy: one_factor
    - domain: 'homeassistant.{{ domain }}'
      policy: one_factor

session:
  name: authelia_session
  domain: '{{ domain }}'
  secret: '{{ auth_session_secret }}'
  expiration: 3600
  inactivity: 300

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
