# redis-exporter
- name: '{{ exporter }} : Add helm repo'
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: '{{ exporter }} : Create chart values file'
  template:
    src: 'exporters/{{ exporter }}/values.yml.j2'
    dest: '{{ paths.root }}/{{ exporter }}/values.yml'

- name: '{{ exporter }} : Apply helm chart with values file'
  kubernetes.core.helm:
    name: '{{ exporter }}'
    chart_ref: 'prometheus-community/prometheus-{{ exporter }}'
    namespace: '{{ role_name }}'
    update_repo_cache: yes
    values_files:
      - '{{ paths.root }}/{{ exporter }}/values.yml'
