---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: true
  values:
    loki:
      image:
        repository: grafana/loki
        tag: '2.6.1'
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      # workaround to fix invalid ruler config error
      rulerConfig:
        storage:
          type: local
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
        lokiCanary:
          enabled: false
    singleBinary:
      extraArgs:
        - -config.expand-env=true
        - -log.level=warn
      extraEnv:
        - name: TZ
          value: ${TIMEZONE}
      persistence:
        storageClass: local-path
    gateway:
      enabled: false
  interval: 10m0s
