---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-redis-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-redis-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: oliver006/redis_exporter
      tag: latest
    env:
      - name: TZ
        value: ${TIMEZONE}
    redisAddress: redis://redis.redis.svc.cluster.local:6379
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      rules: []
  interval: 10m0s
