# directories
- name: Ensure directories exist
  file:
    path: '{{ paths.root }}/{{ role_name }}/{{ item }}.d'
    state: directory
  loop:
    - jail
    - filter
    - action

- name: Copy config directories
  synchronize:
    src: ../files/{{ item }}/
    dest: '{{ paths.root }}/{{ role_name }}/{{ item }}.d'
    delete: yes
  loop:
    - jail
    - filter
    - action
