---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homer
resources:
  - namespace.yaml
  - helm-release.yaml
  - certificate.yaml
  - route.yaml
configMapGenerator:
  - name: homer-config
    files:
      - config.yml
configurations:
  - kustomizeconfig.yaml

