# directories
- name: '{{ service }} : Ensure directories exist'
  file:
    path: '{{ paths.root }}/{{ service }}/{{ item }}'
    state: directory
  loop:
    - provisioning

# configure
- name: '{{ service }} : Copy provisioning files'
  synchronize:
    src: ../files/{{ service }}/provisioning
    dest: '{{ paths.root }}/{{ service }}'
    delete: yes
- include_tasks: '{{ inventory_dir }}/roles/k3s/tasks/manifests.yml'
  vars:
    path: 'services/{{ service }}/secrets'
  loop:
    - auth

# grafana
- name: '{{ service }} : Add helm repo'
  kubernetes.core.helm_repository:
    name: '{{ service }}'
    repo_url: https://grafana.github.io/helm-charts

- name: '{{ service }} : Create chart values file'
  template:
    src: 'services/{{ service }}/values.yml.j2'
    dest: '{{ paths.root }}/{{ service }}/values.yml'

- name: '{{ service }} : Apply helm chart with values file'
  kubernetes.core.helm:
    name: '{{ service }}'
    chart_ref: '{{ service }}/{{ service }}'
    namespace: '{{ role_name }}'
    update_repo_cache: yes
    values_files:
      - '{{ paths.root }}/{{ service }}/values.yml'

# certificate
- include_tasks: '{{ inventory_dir }}/roles/cert-manager/tasks/certificate.yml'
  vars:
    path: 'services/{{ service }}'

# route
- include_tasks: '{{ inventory_dir }}/roles/traefik/tasks/route.yml'
  vars:
    path: 'services/{{ service }}'
