# facts
- name: Gather system facts
  set_fact:
    arm: '{{ ansible_architecture == "armhf" or ansible_architecture == "armv7l" }}'

# configure system
- include_tasks: system.yml

# install common packages
- include_tasks: packages.yml

# install log2ram package
- include_tasks: tools/log2ram.yml
  when: arm
