# common apt packages
- name: Install common packages
  become: yes
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: latest
  loop:
    - vim

# system dependencies for alpine 3.13
- name: Install dependencies for Alpine 3.13
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"
  become: yes
  block:
    - name: Add signing keys
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: '{{ item }}'
        state: present
      loop:
        - 04EE7237B7D453EC
        - 648ACFD622F3D138
    - name: Add buster backports repository
      apt_repository:
        repo: deb http://httpredir.debian.org/debian buster-backports main contrib non-free
        filename: debian-backports
        state: present
    - name: Install dependencies
      apt:
        name: libseccomp2
        default_release: buster-backports
        update_cache: yes
        state: latest

# bash aliases
- name: Create aliases
  lineinfile:
    path: '{{ home_path }}/.bashrc'
    line: 'alias {{ item.alias }}="{{ item.command }}"'
    regexp: 'alias {{ item.alias }}="{{ item.command }}"$'
    insertafter: ^alias
    create: yes
  loop:
    - { alias: 'll', command: 'ls -lisahG' }

# configure vim
- name: Create vim configuration
  template:
    src: vim/.vimrc.j2
    dest: '{{ home_path }}/.vimrc'
