# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - traefik
    - traefik/dynamic
    - authelia

# docker
- name: Create docker-compose file
  template:
    src: docker/{{ ansible_play_name }}/docker-compose.yml.j2
    dest: '{{ root_path }}/docker-compose.yml'

# traefik
- name: Create traefik configuration file
  template:
    src: traefik/traefik.yml.j2
    dest: '{{ root_path }}/traefik/traefik.yml'

- name: Create traefik dynamic configuration files
  template:
    src: traefik/dynamic/{{ item }}.yml.j2
    dest: '{{ root_path }}/traefik/dynamic/{{ item }}.yml'
  when: ansible_play_name == 'network' or ansible_play_name == 'gitlab' and item != 'home-assistant'
  loop:
    - auth
    - security
    - home-assistant
