# configure system
- include_tasks: system.yml
- include_tasks: shell.yml

# install common packages
- include_tasks: packages.yml

# install tools
- include_tasks: tools/vim.yml
- include_tasks: tools/logrotate.yml
- include_tasks: tools/log2ram.yml
  when: arm
