# system dependencies
- name: Install dependencies for Alpine 3.13
  when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"
  become: yes
  block:
    - name: Add signing keys
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: '{{ item }}'
        state: present
      loop:
        - 04EE7237B7D453EC
        - 648ACFD622F3D138
    - name: Add buster backports repository
      apt_repository:
        repo: deb http://httpredir.debian.org/debian buster-backports main contrib non-free
        filename: debian-backports
        state: present
    - name: Install dependencies
      apt:
        name: libseccomp2
        default_release: buster-backports
        update_cache: yes
        state: latest

# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - traefik
    - traefik/dynamic
    - authelia

# docker
- name: Create docker-compose file
  template:
    src: docker/{{ inventory_hostname }}/docker-compose.yml.j2
    dest: '{{ root_path }}/docker-compose.yml'

# traefik
- name: Create traefik configuration file
  template:
    src: traefik/traefik.yml.j2
    dest: '{{ root_path }}/traefik/traefik.yml'

- name: Create traefik dynamic configuration files
  template:
    src: traefik/dynamic/{{ item }}.yml.j2
    dest: '{{ root_path }}/traefik/dynamic/{{ item }}.yml'
  when: inventory_hostname == 'coruscant' or inventory_hostname != 'coruscant' and item != 'home-assistant'
  loop:
    - auth
    - security
    - error-pages
    - home-assistant
