# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - traefik
    - traefik/dynamic
    - authelia

# docker
- name: Create docker-compose file
  template:
    src: ../templates/docker/docker-compose.yml
    dest: '{{ root_path }}/docker-compose.yml'

# traefik
- name: Create traefik configuration file
  template:
    src: ../templates/traefik/traefik.yml
    dest: '{{ root_path }}/traefik.yml'

- name: Create traefik dynamic configuration files
  template:
    src: ../templates/traefik/dynamic/{{ item }}.yml
    dest: '{{ root_path }}/traefik/dynamic/{{ item }}.yml'
  loop:
    - auth
    - home-assistant

# authelia
- name: Create authelia configuration file
  template:
    src: ../templates/authelia/configuration.yml
    dest: '{{ root_path }}/authelia/configuration.yml'

- name: Create authelia users file
  template:
    src: ../templates/authelia/users.yml
    dest: '{{ root_path }}/authelia/users.yml'
