# facts
- name: Gather system facts
  set_fact:
    arm: '{{ ansible_architecture == "armhf" or ansible_architecture == "armv7l" }}'

# configure system
- include_tasks: system.yml
- include_tasks: shell.yml

# install common packages
- include_tasks: packages.yml

# install tools
- include_tasks: tools/vim.yml
- include_tasks: tools/log2ram.yml
  when: arm
