- name: Ensure root directory exists
  file:
    path: '{{ root_path }}'
    state: directory

- name: Create docker-compose file
  template:
    src: ../templates/docker/docker-compose.yml
    dest: '{{ root_path }}/docker-compose.yml'

- name: Create traefik configuration file
  template:
    src: ../templates/traefik/traefik.yml
    dest: '{{ root_path }}/traefik.yml'

- name: Create traefik dynamic configuration files
  template:
    src: ../templates/traefik/dynamic/{{ item }}.yml
    dest: '{{ root_path }}/traefik/dynamic/{{ item }}.yml'
  loop:
    - tls
    - home-assistant
