# configure motd
- name: Configure motd
  become: true
  block:
    - name: Remove default motd
      file:
        path: /etc/motd
        state: absent
    - name: Remove additional motd files
      file:
        path: '/etc/update-motd.d/{{ item }}'
        state: absent
      loop:
        - 10-help-text
        - 50-motd-news
        - 50-landscape-sysinfo
        - 88-esm-announce
    - name: Configure motd file
      template:
        src: motd/motd.j2
        dest: /etc/update-motd.d/89-infrastructure-header
        owner: root
        group: root
        mode: '755'

# configure timezone
- name: Configure timezone
  become: true
  timezone:
    name: '{{ timezone }}'

# configure ssh key
- name: Configure ssh key
  authorized_key:
    state: present
    user: '{{ ansible_user }}'
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/' + ssh.authorized_key) }}"

# configure hostname
- name: Configure hostname
  become: true
  block:
    - name: Set the hostname
      command: hostnamectl set-hostname "{{ inventory_hostname }}"
    - name: Update /etc/hosts with new hostname
      when: arm
      lineinfile:
        path: /etc/hosts
        line: "127.0.1.1\t\traspberrypi {{ inventory_hostname }}"
        regexp: "^127.0.1.1"
        backrefs: yes

# configure static ip
- name: Configure static ip
  when: arm
  become: true
  lineinfile:
    path: /etc/dhcpcd.conf
    line: '{{ item.line }}'
    regexp: '{{ item.regex }}'
  loop:
    - { regex: '^interface eth[0-9]$', line: 'interface eth0' }
    - { regex: '^static ip_address', line: "static ip_address={{ vault.ips[inventory_hostname | replace('.' ~ domains.internal, '')] }}" }
    - { regex: '^static routers', line: 'static routers={{ vault.ips.router }}' }
    - { regex: '^static domain_name_servers', line: 'static domain_name_servers={{ vault.ips.coruscant }}' }
  notify: Reboot

# configure locale
- name: Configure locale
  become: true
  vars:
    locale: en_US.UTF-8
  block:
    - name: Ensure the locale exists
      locale_gen:
        name: '{{ locale }}'
        state: present
    - name: Set locale as default
      command: 'localectl set-locale {{ locale }}'

# configure cgroup directives
- name: Configure cgroup directives
  when: arm
  become: true
  lineinfile:
    path: /boot/cmdline.txt
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    regexp: '((.)+?)(\scgroup_\w+=\w+)*$'
    backrefs: yes
  notify: Reboot

# configure boot config
- name: Configure boot config
  when: arm
  become: true
  lineinfile:
    path: /boot/config.txt
    line: "{{ item.key }}{{ '=' ~ item.value if not item.value }}"
    regexp: "^#?{{ item.key }}="
  loop: '{{ boot_config | dict2items }}'
  notify: Reboot

# configure iptables-legacy
- name: Configure iptables-legacy
  when: arm
  become: true
  block:
    - name: Flush iptables before changing to iptables-legacy
      iptables:
        flush: true
      changed_when: false
    - name: Changing to iptables-legacy
      alternatives:
        path: /usr/sbin/iptables-legacy
        name: iptables
      notify: Reboot
    - name: Changing to ip6tables-legacy
      alternatives:
        path: /usr/sbin/ip6tables-legacy
        name: ip6tables
      notify: Reboot

# expand filesystem
- name: Expand filesystem to fill disk
  when: arm
  become: true
  command: raspi-config --expand-rootfs

# disable swap
- name: Disable swap
  when: arm
  become: true
  block:
    - name: Clear swap
      command: swapoff -a
    - name: Stop swap service
      service:
        name: dphys-swapfile
        state: stopped
      ignore_errors: true
    - name: Disable swap service
      systemd:
        name: dphys-swapfile
        enabled: no
      ignore_errors: true
    - name: Uninstall swap service
      apt:
        name: dphys-swapfile
        state: absent
        purge: yes
