---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: optimizations
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: compression
        namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compression
  namespace: traefik
spec:
  compress: {}
