---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: rate-limit
        namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: traefik
spec:
  rateLimit:
    average: 100
    burst: 50
