- name: Create ingress route
  kubernetes.core.k8s:
    state: present
    template: '{{ path | default(role_name) }}/route.yml.j2'
- name: Create middlewares
  kubernetes.core.k8s:
    state: present
    template: '{{ path | default(role_name) }}/middlewares/{{ middleware }}.yml.j2'
  when: middlewares | default([]) | length > 0
  loop: '{{ middlewares | default([]) }}'
  loop_control:
    loop_var: middleware
