title: Home
path: home
icon: mdi:home
theme: Google - Dark
panel: true
badges: []
cards:
  - type: custom:mod-card
    card:
      type: custom:layout-card
      layout_type: custom:horizontal-layout
      layout:
        max_width: 1000
      cards:
        - type: vertical-stack
          cards:
            - type: custom:swipe-card
              parameters:
                pagination:
                  type: bullets
                mousewheel:
                  forceToAxis: true
                keyboard:
                  enabled: true
                  onlyInViewport: true
              cards:
                - type: media-control
                  entity: media_player.spotify_pascal_iske
                  card_mod:
                    style: |
                      .player, .type-media-control {
                        min-height: 196px;
                      }

                      .background .color-block, .background .no-img, .background .image {
                        background: inherit;
                      }
                - type: media-control
                  entity: media_player.ps4_pi
                  card_mod:
                    style: |
                      .player, .type-media-control {
                        min-height: 196px;
                      }

                      .background .color-block, .background .no-img, .background .image {
                        background: inherit;
                      }
            - type: weather-forecast
              entity: weather.home
            - type: custom:sun-card
              darkMode: true
            - type: sensor
              entity: sensor.rodgau_nieder_roden_to_westend_frankfurt_a_m
              name: S1 → Westend
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              entities:
                - type: custom:multiple-entity-row
                  entity: sensor.tankerkoenig_car_tank_24_e5
                  show_state: false
                  name: Neumann Tankstelle
                  secondary_info: last-changed
                  entities:
                    - entity: sensor.tankerkoenig_car_tank_24_e5
                      name: Gas
                    - entity: sensor.tankerkoenig_car_tank_24_diesel
                      name: Diesel
                - type: custom:multiple-entity-row
                  entity: sensor.tankerkoenig_car_tank_24_e5
                  show_state: false
                  name: Tankcenter Rodgau
                  secondary_info: last-changed
                  entities:
                    - entity: sensor.tankerkoenig_tankcenter_rodgau_e5
                      name: Gas
                    - entity: sensor.tankerkoenig_tankcenter_rodgau_diesel
                      name: Diesel
        - type: vertical-stack
          cards:
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Entrance
                icon: mdi:door
                state_color: false
                show_header_toggle: false
              entities:
                - entity: binary_sensor.entrance_lumi_magnet_on_off
                  secondary_info: last-changed
                  icon: mdi:door
                  name: Door
                - entity: sensor.entrance_lumi_magnet_power
                  secondary_info: last-changed
                  name: Battery
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Living Room
                icon: mdi:sofa
                state_color: true
                show_header_toggle: true
              entities:
                - entity: sensor.living_room_lumi_temperature
                  secondary_info: last-changed
                  name: Temperature
                - entity: sensor.living_room_lumi_humidity
                  secondary_info: last-changed
                  name: Humidity
                - entity: sensor.living_room_lumi_power
                  secondary_info: last-changed
                  name: Battery
                - type: custom:text-divider-row
                  entity: sensor.time
                  text: Lights
                  card_mod:
                    style: |
                      h2.text-divider {
                        margin: 0;
                        font-weight: normal;
                        letter-spacing: 0.5px;
                        opacity: .5;
                      }

                      h2.text-divider span {
                        padding: 10px 1em;
                      }
                - entity: switch.lampe
                  secondary_info: last-changed
                - entity: switch.duftlampe
                  secondary_info: last-changed
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Kitchen
                icon: mdi:pot-steam
                state_color: true
                show_header_toggle: true
              entities:
                - entity: switch.lichterkette
                  secondary_info: last-changed
        - type: vertical-stack
          cards:
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Bedroom
                icon: mdi:bed
                state_color: true
                show_header_toggle: true
              entities:
                - entity: sensor.bed_room_lumi_temperature
                  secondary_info: last-changed
                  name: Temperature
                - entity: sensor.bed_room_lumi_humidity
                  secondary_info: last-changed
                  name: Humidity
                - entity: sensor.bed_room_lumi_power
                  secondary_info: last-changed
                  name: Battery
                - type: custom:text-divider-row
                  entity: sensor.time
                  text: Lights
                  card_mod:
                    style: |
                      h2.text-divider {
                        margin: 0;
                        font-weight: normal;
                        letter-spacing: 0.5px;
                        opacity: .5;
                      }

                      h2.text-divider span {
                        padding: 10px 1em;
                      }
                - entity: switch.licht
                  secondary_info: last-changed
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Childrens Room
                icon: mdi:baby-face
                state_color: true
                show_header_toggle: true
              entities:
                - entity: sensor.childrens_room_lumi_temperature
                  secondary_info: last-changed
                  name: Temperature
                - entity: sensor.childrens_room_lumi_humidity
                  secondary_info: last-changed
                  name: Humidity
                - entity: sensor.childrens_room_lumi_power
                  secondary_info: last-changed
                  name: Battery
                - type: custom:text-divider-row
                  entity: sensor.time
                  text: Lights
                  card_mod:
                    style: |
                      h2.text-divider {
                        margin: 0;
                        font-weight: normal;
                        letter-spacing: 0.5px;
                        opacity: .5;
                      }

                      h2.text-divider span {
                        padding: 10px 1em;
                      }
                - entity: switch.love
                  secondary_info: last-changed
                - entity: switch.kugel
                  secondary_info: last-changed
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Bathroom
                icon: mdi:shower
                state_color: true
                show_header_toggle: true
              entities:
                - entity: sensor.bathroom_lumi_temperature
                  secondary_info: last-changed
                  name: Temperature
                - entity: sensor.bathroom_lumi_humidity
                  secondary_info: last-changed
                  name: Humidity
                - entity: sensor.bathroom_lumi_power
                  secondary_info: last-changed
                  name: Battery
    card_mod:
      style: |
        ha-card {
          max-width: calc(100% + 7px);
          margin-top: -8px;
          margin-right: -8px;
          margin-left: -7px;
          transition: none;
        }
