title: Home
path: home
icon: mdi:home
theme: Google - Dark
panel: true
badges: []
cards:
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.spotify_pascal_iske
            style: |
              .background .color-block, .background .no-img, .background .image {
                background: inherit;
              }
          - type: weather-forecast
            entity: weather.home
          - type: sensor
            entity: sensor.rodgau_nieder_roden_to_westend_frankfurt_a_m
            name: S1 → Westend
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Weight Pascal
                graph: line
                icon: mdi:scale-bathroom
                hours_to_show: 168
                entity: sensor.withings_weight_kg_pascal_iske_2
              - type: sensor
                name: Weight Sarah
                graph: line
                icon: mdi:scale-bathroom
                hours_to_show: 168
                entity: sensor.withings_weight_kg_sarah_iske_2
      - type: vertical-stack
        cards:
          - type: entities
            title: Living Room
            state_color: true
            show_header_toggle: true
            entities:
              - entity: switch.kugel
              - entity: switch.lampe
              - entity: switch.duftlampe
          - type: entities
            title: Bedroom
            state_color: true
            show_header_toggle: true
            entities:
              - entity: switch.licht
              - entity: switch.love
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Temperature
                graph: line
                hours_to_show: 48
                entity: sensor.lumi_lumi_weather_temperature
              - type: sensor
                name: Humidity
                graph: line
                hours_to_show: 48
                entity: sensor.lumi_lumi_weather_humidity
              - type: sensor
                name: Pressure
                graph: line
                hours_to_show: 48
                entity: sensor.lumi_lumi_weather_pressure
          - type: entity-filter
            show_empty: false
            state_filter:
              - operator: '!='
                value: 'unavailable'
            card:
              title: Printer
              icon: mdi:printer
              show_header_toggle: false
            entities:
              - entity: sensor.epson_et_2750_series
              - entity: sensor.epson_et_2750_series_black_ink
              - entity: sensor.epson_et_2750_series_cyan_ink
              - entity: sensor.epson_et_2750_series_magenta_ink
              - entity: sensor.epson_et_2750_series_yellow_ink
      - type: vertical-stack
        cards:
          - type: sensor
            name: Public IP
            graph: none
            icon: mdi:web
            entity: sensor.fritzbox_public_ip
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Downstream
                graph: none
                icon: mdi:arrow-down
                entity: sensor.fritzbox_downstream_percentage
              - type: sensor
                name: Upstream
                graph: none
                icon: mdi:arrow-up
                entity: sensor.fritzbox_upstream_percentage
              - type: sensor
                name: Uptime
                graph: none
                icon: mdi:clock-outline
                entity: sensor.fritzbox_uptime
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Last Boot
                graph: none
                icon: mdi:clock-outline
                entity: sensor.relative_last_boot
