title: Network
path: network
icon: mdi:server-network
theme: Google - Dark
panel: true
badges: []
cards:
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Public IP
                graph: none
                icon: mdi:web
                entity: sensor.fritzbox_public_ip
              - type: sensor
                name: Last Boot
                graph: none
                icon: mdi:clock-outline
                entity: sensor.relative_last_boot
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Downstream
                graph: none
                icon: mdi:arrow-down
                entity: sensor.fritzbox_downstream_percentage
              - type: sensor
                name: Upstream
                graph: none
                icon: mdi:arrow-up
                entity: sensor.fritzbox_upstream_percentage
              - type: sensor
                name: Uptime
                graph: none
                icon: mdi:clock-outline
                entity: sensor.fritzbox_uptime
          - type: entity-filter
            show_empty: false
            state_filter:
              - operator: '!='
                value: 'unavailable'
            card:
              title: Printer
              icon: mdi:printer
              show_header_toggle: false
            entities:
              - entity: sensor.epson_et_2750_series
              - entity: sensor.epson_et_2750_series_black_ink
              - entity: sensor.epson_et_2750_series_cyan_ink
              - entity: sensor.epson_et_2750_series_magenta_ink
              - entity: sensor.epson_et_2750_series_yellow_ink
      - type: vertical-stack
        cards:
          - type: entities
            title: Ad Blocker
            show_header_toggle: false
            entities:
              - entity: switch.pi_hole
                type: custom:multiple-entity-row
                name: Enabled
                secondary_info: last-changed
                toggle: true
                tap_action:
                  action: url
                  url_path: !secret pi_hole_url
                entities:
                  - entity: sensor.pi_hole_ads_percentage_blocked_today
                    name: Percentage
                  - entity: sensor.pi_hole_ads_blocked_today
                    name: Queries
                    unit: false
                  - entity: sensor.pi_hole_domains_blocked
                    name: Blocklist
                    unit: false
              - type: divider
                style: |
                  div {
                    height: 10px;
                  }
            footer:
              type: graph
              entity: sensor.pi_hole_ads_percentage_blocked_today
              hours_to_show: 168
