title: Kitchen
path: kitchen
icon: mdi:pot-steam
theme: Google - Dark
panel: true
badges: []
cards:
  - type: custom:mod-card
    card:
      type: custom:layout-card
      layout_type: custom:horizontal-layout
      layout:
        max_width: 1000
      cards:
        - type: vertical-stack
          cards:
            - type: entities
              title: Lights
              state_color: true
              show_header_toggle: true
              entities:
                - entity: switch.lichterkette
                  secondary_info: last-changed
    card_mod:
      style: |
        ha-card {
          margin-top: -8px;
          margin-right: -8px;
          margin-left: -7px;
          transition: none;
        }
