---
- name: Reload Prometheus
  uri:
    url: 'https://prometheus.{{ domain }}/-/reload'
    method: POST
    validate_certs: false
- name: Reload Alertmanager
  uri:
    url: 'https://alerts.{{ domain }}/-/reload'
    method: POST
    validate_certs: false
