---
watchtower_schedule: '0 0 0 * * *'
watchtower_slack_level: info
watchtower_slack_url: "slack://watchtower@{{ lookup('env', 'WATCHTOWER_SLACK_TOKENS') }}"
watchtower_slack_template: "{{ '{{range .}}[' ~ ansible_play_name ~ '] {{.Message}}{{println}}{{end}}' }}"
watchtower_http_api_token: "{{ lookup('env', 'WATCHTOWER_HTTP_API_TOKEN') }}"
watchtower_http_api_metrics: "true"
watchtower_cleanup: "true"
watchtower_debug: "false"
digital_ocean_token: "{{ lookup('env', 'DIGITAL_OCEAN_TOKEN') }}"
auth_username: "{{ lookup('env', 'AUTH_USERNAME') }}"
auth_password: "{{ lookup('env', 'AUTH_PASSWORD') }}"
auth_email: "{{ lookup('env', 'AUTH_EMAIL') }}"
auth_display_name: "{{ lookup('env', 'AUTH_DISPLAY_NAME') }}"
auth_jwt_secret: "{{ lookup('env', 'AUTH_JWT_SECRET') }}"
auth_session_secret: "{{ lookup('env', 'AUTH_SESSION_SECRET') }}"
auth_smtp_host: "{{ lookup('env', 'AUTH_SMTP_HOST') }}"
auth_smtp_port: "{{ lookup('env', 'AUTH_SMTP_PORT') }}"
auth_smtp_email: "{{ lookup('env', 'AUTH_SMTP_EMAIL') }}"
auth_smtp_password: "{{ lookup('env', 'AUTH_SMTP_PASSWORD') }}"
