- name: Update Masters
  hosts: masters
  become: true
  tasks:
    - name: Update apt packages
      apt:
        upgrade: safe
        update_cache: yes
        autoremove: yes
      tags:
        - masters

- name: Update Workers
  hosts: workers
  become: true
  tasks:
    - name: Update apt packages
      apt:
        upgrade: safe
        update_cache: yes
        autoremove: yes
      tags:
        - workers
