---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  chart:
    spec:
      chart: node-problem-detector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: flux-system
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
  interval: 10m0s
