# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - '{{ role_name }}'
    - '{{ folder }}'

# namespace
- name: Create a namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: '{{ role_name }}'
    state: present

# code-server
- name: Add helm repo
  kubernetes.core.helm_repository:
    name: pascaliske
    repo_url: https://charts.pascaliske.dev

- name: Create chart values file
  template:
    src: '{{ role_name }}/values.yml.j2'
    dest: '{{ root_path }}/{{ role_name }}/values.yml'

- name: Apply helm chart with values file
  kubernetes.core.helm:
    name: '{{ role_name }}'
    chart_ref: 'pascaliske/{{ role_name }}'
    namespace: '{{ role_name }}'
    update_repo_cache: yes
    values_files:
      - '{{ root_path }}/{{ role_name }}/values.yml'

# route
- name: Create ingress route
  kubernetes.core.k8s:
    state: present
    template: '{{ role_name }}/route.yml.j2'
