# speedtest-exporter
- name: '{{ exporter }} : Add helm repo'
  kubernetes.core.helm_repository:
    name: k8s-at-home
    repo_url: https://k8s-at-home.com/charts

- name: '{{ exporter }} : Create chart values file'
  template:
    src: 'exporters/{{ exporter }}/values.yml.j2'
    dest: '{{ root_path }}/{{ exporter }}/values.yml'

- name: '{{ exporter }} : Apply helm chart with values file'
  kubernetes.core.helm:
    name: '{{ exporter }}'
    chart_ref: 'k8s-at-home/{{ exporter }}'
    namespace: '{{ role_name }}'
    update_repo_cache: yes
    values_files:
      - '{{ root_path }}/{{ exporter }}/values.yml'
