name: Ansible
on:
  push:
    branches:
      - master
    paths:
      - 'ansible/**'
  pull_request:
    branches:
      - master
    paths:
      - 'ansible/**'

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3

      # lint ansible
      - uses: ansible-community/ansible-lint-action@v6
        with:
          path: |
            ansible/**/*.yml
