name: Config Check
on: push

jobs:
  check_prometheus:
    name: Prometheus
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2.3.4

      # prepare
      - name: Prepare configuration files
        run: |
          cp roles/monitoring/{templates/prometheus/alert.rules.j2,files/alert.rules}
          cp roles/monitoring/{templates/prometheus/prometheus.yml.j2,files/prometheus.yml}

      # check prometheus config
      - uses: addnab/docker-run-action@v3
        with:
          image: dnanexus/promtool:2.9.2
          options: -v ${{ github.workspace }}/roles/monitoring/files:/tmp
          run: promtool check config /tmp/prometheus.yml

  check_home_assistant:
    name: Home Assistant
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2.3.4

      # prepare
      - name: Prepare configuration files
        run: |
          sed -E -i 's/!secret ([a-z0-9_]+)/"\1"/' roles/home-assistant/files/*.yaml
          sed -E -i 's/!secret ([a-z0-9_]+)/"\1"/' roles/home-assistant/files/**/*.yaml
          sed -i 's/breaking_changes/# breaking_changes/g' roles/home-assistant/files/integrations/core.yaml
          mv roles/home-assistant/files/integrations/http.yaml{,.disabled}
          mv roles/home-assistant/files/integrations/withings.yaml{,.disabled}
          mv roles/home-assistant/files/automations/battery-check.yaml{,.disabled}
          mv roles/home-assistant/files/automations/bed-room-mini-switch.yaml{,.disabled}
          mv roles/home-assistant/files/automations/love-mini-switch.yaml{,.disabled}
          git ls-files -m

      # check prometheus config
      - uses: addnab/docker-run-action@v3
        with:
          image: homeassistant/home-assistant:stable
          options: -v ${{ github.workspace }}/roles/home-assistant/files:/config
          run: hass --script check_config --config /config
