name: Config Check
on: push

jobs:
  check-prometheus:
    name: Prometheus
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2.4.0

      # prepare
      - name: Prepare variables file
        run: |
          cat << EOF > ${{ github.workspace }}/data.yml
          vault:
            home_assistant:
              access_token: ''
          EOF
      - name: Prepare configuration file
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: roles/monitoring/templates/services/prometheus/config.yml.j2
          output_file: ${{ github.workspace }}/prometheus.yml
          data_file: ${{ github.workspace }}/data.yml
      - name: Prepare alert rules
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: roles/monitoring/templates/services/prometheus/rules.yml.j2
          output_file: ${{ github.workspace }}/alert.rules
          data_file: ${{ github.workspace }}/data.yml
      - name: Remove k8s certificate references
        run: |
          sed -E -i 's/ca_file/# ca_file/' ${{ github.workspace }}/prometheus.yml
          sed -E -i 's/bearer_token_file/# bearer_token_file/' ${{ github.workspace }}/prometheus.yml

      # check prometheus config
      - uses: addnab/docker-run-action@v3
        with:
          image: dnanexus/promtool:2.9.2
          options: -v ${{ github.workspace }}:/tmp
          run: promtool check config /tmp/prometheus.yml

  check-alertmanager:
    name: Alertmanager
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2.4.0

      # prepare
      - name: Prepare variables file
        run: |
          cat << EOF > ${{ github.workspace }}/data.yml
          vault:
            alertmanager:
              slack:
                channel: ''
                username: ''
                tokens: ''
          EOF
      - name: Prepare configuration file
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: roles/monitoring/templates/services/alertmanager/config.yml.j2
          output_file: ${{ github.workspace }}/alertmanager.yml
          data_file: ${{ github.workspace }}/data.yml
      - name: Prepare template file
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: roles/monitoring/templates/services/alertmanager/templates/slack.tmpl.j2
          output_file: ${{ github.workspace }}/slack.tmpl
          data_file: ${{ github.workspace }}/data.yml

      # check alertmanager config
      - uses: addnab/docker-run-action@v3
        with:
          image: prom/alertmanager:latest
          options: -v ${{ github.workspace }}:/etc/alertmanager
          run: /bin/amtool check-config /etc/alertmanager/alertmanager.yml

  check-home-assistant:
    name: Home Assistant
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2.4.0

      # prepare
      - name: Prepare configuration files
        run: |
          sed -E -i 's/!secret ([a-z0-9_]+)/"\1"/' roles/home-assistant/files/*.yaml
          sed -E -i 's/!secret ([a-z0-9_]+)/"\1"/' roles/home-assistant/files/**/*.yaml
          mv roles/home-assistant/files/integrations/homekit.yaml{,.disabled}
          mv roles/home-assistant/files/integrations/http.yaml{,.disabled}
          mv roles/home-assistant/files/integrations/withings.yaml{,.disabled}
          mv roles/home-assistant/files/automations/battery-check.yaml{,.disabled}
          mv roles/home-assistant/files/automations/bedroom-mini-switch.yaml{,.disabled}
          mv roles/home-assistant/files/automations/love-mini-switch.yaml{,.disabled}
          git ls-files -m

      # check prometheus config
      - uses: addnab/docker-run-action@v3
        with:
          image: homeassistant/home-assistant:stable
          options: -v ${{ github.workspace }}/roles/home-assistant/files:/config
          run: hass --script check_config --config /config
