name: Linting
on: push

jobs:
  lint-ansible:
    name: Ansible
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3

      # lint ansible
      - uses: ansible-community/ansible-lint-action@v6
        with:
          path: |
            playbooks/**/*.yml
            roles/**/tasks/*.yml
            roles/**/handlers/*.yml
