name: Linting
on: push

jobs:
  lint-terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3

      # setup taskfile
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # setup terraform
      - uses: hashicorp/setup-terraform@v2

      # setup tflint
      - uses: terraform-linters/setup-tflint@v3

      # init terraform
      - name: Init Terraform
        run: task tf:init -- -backend=false

      # validate terraform
      - name: Validate Terraform
        run: task tf:validate

      # lint terraform
      - name: Lint Terraform
        run: task tf:lint

  lint-ansible:
    name: Ansible
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3

      # lint ansible
      - uses: ansible-community/ansible-lint-action@v6
        with:
          path: |
            playbooks/**/*.yml
            roles/**/tasks/*.yml
            roles/**/handlers/*.yml
