# directories
- name: Ensure directories exist
  file:
    path: '{{ paths.root }}/{{ item }}'
    state: directory
  loop:
    - '{{ role_name }}'

# namespace
- include_tasks: '{{ inventory_dir }}/roles/k3s/tasks/namespace.yml'

# configuration
- include_tasks: '{{ inventory_dir }}/roles/k3s/tasks/manifests.yml'
  loop:
    - secrets/auth

# pihole
- name: Add helm repo
  kubernetes.core.helm_repository:
    name: mojo2600
    repo_url: https://mojo2600.github.io/pihole-kubernetes/

- name: Create chart values file
  template:
    src: '{{ role_name }}/values.yml.j2'
    dest: '{{ paths.root }}/{{ role_name }}/values.yml'

- name: Apply helm chart with values file
  kubernetes.core.helm:
    name: '{{ role_name }}'
    chart_ref: 'mojo2600/{{ role_name }}'
    namespace: '{{ role_name }}'
    update_repo_cache: yes
    values_files:
      - '{{ paths.root }}/{{ role_name }}/values.yml'

# route
- include_tasks: '{{ inventory_dir }}/roles/traefik/tasks/route.yml'
  vars:
    middlewares:
      - headers
      - prefix
