# directories
- name: Ensure directories exist
  file:
    path: '{{ root_path }}/{{ item }}'
    state: directory
  loop:
    - '{{ role_name }}'

# namespace
- name: Create a namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: '{{ role_name }}'
    state: present

# configuration
- name: Create secret manifests
  kubernetes.core.k8s:
    state: present
    template: '{{ role_name }}/secrets/{{ item }}.yml.j2'
  loop:
    - auth

# pihole
- name: Add helm repo
  kubernetes.core.helm_repository:
    name: mojo2600
    repo_url: https://mojo2600.github.io/pihole-kubernetes/

- name: Create chart values file
  template:
    src: '{{ role_name }}/values.yml.j2'
    dest: '{{ root_path }}/{{ role_name }}/values.yml'

- name: Apply helm chart with values file
  kubernetes.core.helm:
    name: '{{ role_name }}'
    chart_ref: 'mojo2600/{{ role_name }}'
    namespace: '{{ role_name }}'
    update_repo_cache: yes
    values_files:
      - '{{ root_path }}/{{ role_name }}/values.yml'

# route
- name: Create middleware manifests
  kubernetes.core.k8s:
    state: present
    template: '{{ role_name }}/middlewares/{{ item }}.yml.j2'
  loop:
    - headers
    - prefix
- name: Create ingress route
  kubernetes.core.k8s:
    state: present
    template: '{{ role_name }}/route.yml.j2'
