- name: Ensure config directories exists
  file:
    path: '{{ root_path }}/{{ role_name }}'
    state: directory

- name: Copy Pihole files to config directory
  copy:
    src: ../files/
    dest: '{{ root_path }}/{{ role_name }}'
