alias: Disk Use Alarm
trigger:
  platform: numeric_state
  entity_id: sensor.disk_use_percent
  above: 90
action:
  - service: notify.slack
    data_template:
      title: Hard Drive Monitor
      message: >
        Network Controller is running out of space: {{ states('sensor.disk_use_percent') }}%
  - service: persistent_notification.create
    data_template:
      title: Hard Drive Monitor
      message: >
        Network Controller is running out of space: {{ states('sensor.disk_use_percent') }}%
      notification_id: "Hard Drive Monitor"
