alias: Send Notification on Startup
trigger:
  platform: homeassistant
  event: start
action:
  - service: notify.mobile_app_pascaliske
    data:
      title: Home Assistant
      message: Home Assistant has been started successfully!
